# .coderabbit.yaml

# Enable CodeRabbit on pull requests to these branches
trigger:
  pull_request:
    branches:
      - main
      - dev

# General review settings
review:
  enable: true
  summary: true
  suggestions: true
  approve_on_pass: false

# Optional: Exclude files or directories from review
exclude:
  - 'docs/**'
  - '*.md'
  - '*.mdc'

# Optional: Custom review prompt (uncomment to use)
prompt: |
  Please review this pull request for code quality, security, and adherence to best practices.
