
  /**
  * Generated by @proofgeist/fmdapi package
  * https://github.com/proofgeist/fmdapi
  * DO NOT EDIT THIS FILE DIRECTLY. Changes may be overritten
  */
  import { z } from "zod";

  // @generated
  // prettier-ignore
  /* eslint-disable */
  export const ZBookings = z.object({
      "CreatedBy": z.string(),
      "CreationTimestamp": z.string(),
      "id": z.string(),
      "ItemType": z.string(),
      "ModificationTimestamp": z.string(),
      "ModifiedBy": z.string(),
      "ShipFrom": z.string(),
      "ShipNumber": z.string(),
      "ShipTo": z.string(),
  });

  export type TBookings = z.infer<typeof ZBookings>;
