
  /**
  * Generated by @proofgeist/fmdapi package
  * https://github.com/proofgeist/fmdapi
  * DO NOT EDIT THIS FILE DIRECTLY. Changes may be overritten
  */
  import { z } from "zod";

  // @generated
  // prettier-ignore
  /* eslint-disable */
  export const ZBookings = z.object({
      "_GMT#": z.string(),
      "_Booking#": z.string(),
      "portOfDischargeCity": z.string(),
      "portOfDischargeCountry": z.string(),
      "placeOfDeliveryCity": z.string(),
      "placeOfDeliveryCountry": z.string(),
      "ETDDatePort": z.string(),
      "ETADatePort": z.string(),
      "ETADateCity": z.string(),
      "reportReferenceCustomer": z.string(),
  });

  export type TBookings = z.infer<typeof ZBookings>;
