
  /**
  * Generated by @proofgeist/fmdapi package
  * https://github.com/proofgeist/fmdapi
  * DO NOT EDIT THIS FILE DIRECTLY. Changes may be overritten
  */
  import { z } from "zod";

  // @generated
  // prettier-ignore
  /* eslint-disable */
  export const ZBookingsReport = z.object({
      "<No Access>": z.string(),
  });

  export type TBookingsReport = z.infer<typeof ZBookingsReport>;
