
  /**
  * Generated by @proofgeist/fmdapi package
  * https://github.com/proofgeist/fmdapi
  * DO NOT EDIT THIS FILE DIRECTLY. Changes may be overritten
  */
  import { z } from "zod";

  // @generated
  // prettier-ignore
  /* eslint-disable */
  export const ZInquiries = z.object({
      "companyName": z.string(),
      "lastName": z.string(),
      "firstName": z.string(),
      "emailAddress": z.string(),
      "phoneNumber": z.string(),
      "message": z.string(),
      "__id": z.string(),
  });

  export type TInquiries = z.infer<typeof ZInquiries>;
