/**
 * Generated by @proofgeist/fmdapi package
 * https://github.com/proofgeist/fmdapi
 * DO NOT EDIT THIS FILE DIRECTLY. Changes may be overritten
 */

// @generated
// prettier-ignore
/* eslint-disable */
export type TemailVerification = {
      "id": string,
      "email": string,
      "id_user": string,
      "code": string,
      "expires_at": number | null,
  };
