
  /**
  * Generated by @proofgeist/fmdapi package
  * https://github.com/proofgeist/fmdapi
  * DO NOT EDIT THIS FILE DIRECTLY. Changes may be overritten
  */

  // @generated
  // prettier-ignore
  /* eslint-disable */
  export type Tsessions = {
      "id": string,
      "expiresAt": number | null,
      "id_user": string,
      "proofkit_auth_users::email": string,
      "proofkit_auth_users::emailVerified": number | null,
      "proofkit_auth_users::username": string,
      "proofkit_auth_users::contact_id": string,
      "pka_company::reportReferenceCustomer": string,
  };
