/**
 * Generated by @proofgeist/fmdapi package
 * https://github.com/proofgeist/fmdapi
 * DO NOT EDIT THIS FILE DIRECTLY. Changes may be overritten
 */

// @generated
// prettier-ignore
/* eslint-disable */
export type Tusers = {
      "id": string,
      "email": string,
      "emailVerified": number | null,
      "username": string,
      "password_hash": string,
      "company_id": string,
  };
